INSERT INTO Members(Name) VALUES ('Angyal-Cseke Csaba')
INSERT INTO Members(Name) VALUES ('Bagi-Misják Petra')
INSERT INTO Members(Name) VALUES ('Balás Eszter')
INSERT INTO Members(Name) VALUES ('Bence Áron')
INSERT INTO Members(Name) VALUES ('Bence Gábor')
INSERT INTO Members(Name) VALUES ('Bence Zsófi Anna')
INSERT INTO Members(Name) VALUES ('Bencsné Bokányi Eszter')
INSERT INTO Members(Name) VALUES ('Benda György')
INSERT INTO Members(Name) VALUES ('Béres Márk')
INSERT INTO Members(Name) VALUES ('Bódiss Tamás')
INSERT INTO Members(Name) VALUES ('Borsos Miklós')
INSERT INTO Members(Name) VALUES ('Brolly Áron')
INSERT INTO Members(Name) VALUES ('Bujtár-Buza Zsófia')
INSERT INTO Members(Name) VALUES ('Csepregi Dorka')
INSERT INTO Members(Name) VALUES ('Csepregi Gyõzõ')
INSERT INTO Members(Name) VALUES ('Csernyik Balázs')
INSERT INTO Members(Name) VALUES ('Danis (Soltész) Petra')
INSERT INTO Members(Name) VALUES ('Dévényi-Gyõrffy Imola')
INSERT INTO Members(Name) VALUES ('Dibusz Ferenc')
INSERT INTO Members(Name) VALUES ('Ecsedi Klára')
INSERT INTO Members(Name) VALUES ('Fekete Ádámné Ecsedi Katalin')
INSERT INTO Members(Name) VALUES ('Fekete Anikó')
INSERT INTO Members(Name) VALUES ('Ferenczi Zsolt')
INSERT INTO Members(Name) VALUES ('Gadó Benedek')
INSERT INTO Members(Name) VALUES ('Gadóné Kézdy Edit')
INSERT INTO Members(Name) VALUES ('Gion Kata')
INSERT INTO Members(Name) VALUES ('Gion Zsuzsa')
INSERT INTO Members(Name) VALUES ('Gombkötõ Beáta')
INSERT INTO Members(Name) VALUES ('Gombos (Bence) Kata')
INSERT INTO Members(Name) VALUES ('Gombos Arikán')
INSERT INTO Members(Name) VALUES ('Hacknauer Bettina')
INSERT INTO Members(Name) VALUES ('Halmi Krisztina SJC')
INSERT INTO Members(Name) VALUES ('Haris Zsófia')
INSERT INTO Members(Name) VALUES ('Herboly Bendegúz')
INSERT INTO Members(Name) VALUES ('Hoffmann Ágnes')
INSERT INTO Members(Name) VALUES ('Hunyák (Farkas) Erika')
INSERT INTO Members(Name) VALUES ('Iker Julianna')
INSERT INTO Members(Name) VALUES ('Ittzés András')
INSERT INTO Members(Name) VALUES ('Ittzés Máté')
INSERT INTO Members(Name) VALUES ('Johann Panna')
INSERT INTO Members(Name) VALUES ('Johansson Abaffy Nóra')
INSERT INTO Members(Name) VALUES ('Kanizsár Dorottya')
INSERT INTO Members(Name) VALUES ('Kecskés D. Vértesy Júlia')
INSERT INTO Members(Name) VALUES ('Kéménczy Antal')
INSERT INTO Members(Name) VALUES ('Kérges Barnabás')
INSERT INTO Members(Name) VALUES ('Kérges Dániel')
INSERT INTO Members(Name) VALUES ('Kesselyák Bence')
INSERT INTO Members(Name) VALUES ('Kis Benedek')
INSERT INTO Members(Name) VALUES ('Kiss Renáta')
INSERT INTO Members(Name) VALUES ('Kiss Zsuzsanna')
INSERT INTO Members(Name) VALUES ('Klein Ferenc')
INSERT INTO Members(Name) VALUES ('Kolba Gábor')
INSERT INTO Members(Name) VALUES ('Kolba Hajnalka')
INSERT INTO Members(Name) VALUES ('Kotsis Domokos')
INSERT INTO Members(Name) VALUES ('Kovácsné Végh Julianna')
INSERT INTO Members(Name) VALUES ('Kretz István')
INSERT INTO Members(Name) VALUES ('Kulcsár (Bokros) Virág Kata')
INSERT INTO Members(Name) VALUES ('Kutschi Renáta')
INSERT INTO Members(Name) VALUES ('La-Torre Krisztina')
INSERT INTO Members(Name) VALUES ('Lencsés Jánosné Balás Dóra Katalin')
INSERT INTO Members(Name) VALUES ('Mády Katalin')
INSERT INTO Members(Name) VALUES ('Mechler Anna')
INSERT INTO Members(Name) VALUES ('Megyesi Zoltán')
INSERT INTO Members(Name) VALUES ('Megyesi Zsófia')
INSERT INTO Members(Name) VALUES ('Mekis Péter')
INSERT INTO Members(Name) VALUES ('Melis Kinga')
INSERT INTO Members(Name) VALUES ('Mészáros AnZsó')
INSERT INTO Members(Name) VALUES ('Miklósné Székács Judit')
INSERT INTO Members(Name) VALUES ('Molnár Lilla')
INSERT INTO Members(Name) VALUES ('Nagy Ákos')
INSERT INTO Members(Name) VALUES ('Nagy Bertalan')
INSERT INTO Members(Name) VALUES ('Németh Pál')
INSERT INTO Members(Name) VALUES ('Németh Sándor')
INSERT INTO Members(Name) VALUES ('Németh Zsuzsa')
INSERT INTO Members(Name) VALUES ('Nováky Andrea')
INSERT INTO Members(Name) VALUES ('Opicz József')
INSERT INTO Members(Name) VALUES ('Pálmai Árpád')
INSERT INTO Members(Name) VALUES ('Pap Anna Inkeri')
INSERT INTO Members(Name) VALUES ('Pap Kinga Marjatta')
INSERT INTO Members(Name) VALUES ('Plaveczné Gyõri Katalin Dorottya')
INSERT INTO Members(Name) VALUES ('Pócs Miklós')
INSERT INTO Members(Name) VALUES ('Remenár (Kocsis) Krisztina')
INSERT INTO Members(Name) VALUES ('Rohloff (Gyõri) Noémi')
INSERT INTO Members(Name) VALUES ('Rozsnyai Gábor')
INSERT INTO Members(Name) VALUES ('Rumy Balázs')
INSERT INTO Members(Name) VALUES ('Simon Barbara')
INSERT INTO Members(Name) VALUES ('Somogyi Anna')
INSERT INTO Members(Name) VALUES ('Szabó Tímea')
INSERT INTO Members(Name) VALUES ('Széchey Orsolya')
INSERT INTO Members(Name) VALUES ('Szunyoghy Dóra')
INSERT INTO Members(Name) VALUES ('Szûcs Petra')
INSERT INTO Members(Name) VALUES ('Táborszkyné Ruthner Judit')
INSERT INTO Members(Name) VALUES ('Thurnay Viola')
INSERT INTO Members(Name) VALUES ('Torma Tamás')
INSERT INTO Members(Name) VALUES ('Tuppurainen Outi')
INSERT INTO Members(Name) VALUES ('Tüzes Ágoston')
INSERT INTO Members(Name) VALUES ('Tüzes Johanna')
INSERT INTO Members(Name) VALUES ('Tüzes Marcell')
INSERT INTO Members(Name) VALUES ('Vági Levente')
INSERT INTO Members(Name) VALUES ('Végh András')
INSERT INTO Members(Name) VALUES ('Végh Anna')
INSERT INTO Members(Name) VALUES ('Zalatnay Lídia')
