INSERT INTO Pieces (Composer, Title) VALUES ('Aichinger, Gregor (1565–1628)', 'Merre van Ábel? SAB')
INSERT INTO Pieces (Composer, Title) VALUES ('Anerio, Felice (1560–1614)', 'Christus factus est SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Árokháty Béla (1890–1942)', 'Szívemet hozzád emelem – 25. genfi zsoltár SSA')
INSERT INTO Pieces (Composer, Title) VALUES ('Bach, Johann Sebastian (1685–1750)', 'A menny Urának tisztelet SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Bach, Johann Sebastian (1685–1750)', 'Bleib bei uns BWV 6 kantáta 1. tétel SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Bach, Johann Sebastian (1685–1750)', 'Ein feste Burg ist unser Gott BWV 80 kantáta 5. és 8. tétel SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Bach, Johann Sebastian (1685–1750)', 'Heilig, heilig, heilig SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Bach, Johann Sebastian (1685–1750)', 'Herr Christ, der ein''ge Gottessohn BWV 96 kantáta')
INSERT INTO Pieces (Composer, Title) VALUES ('Bach, Johann Sebastian (1685–1750)', 'Höchsterwünschtes Freudenfest BWV 194 kantáta')
INSERT INTO Pieces (Composer, Title) VALUES ('Bach, Johann Sebastian (1685–1750)', 'Ich, elender Mensch BWV 48 kantáta')
INSERT INTO Pieces (Composer, Title) VALUES ('Bach, Johann Sebastian (1685–1750)', 'Jesu, meine Freude SSATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Bach, Johann Sebastian (1685–1750)', 'Készülj, lelkem, Jézusodhoz SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Bach, Johann Sebastian (1685–1750)', 'Ki dolgát mind az Úrra hagyja SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Bach, Johann Sebastian (1685–1750)', 'Krisztus, ártatlan Bárány SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Bach, Johann Sebastian (1685–1750)', 'Kyrie, Gott Vater in Ewigkeit SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Bach, Johann Sebastian (1685–1750)', 'Lobet den Herrn, alle Heiden SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Bach, Johann Sebastian (1685–1750)', 'Mint égből tiszta hó SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Bach, Johann Sebastian (1685–1750)', 'Mit Isten akar énvelem SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Bach, Johann Sebastian (1685–1750)', 'Nun komm, der Heiden Heiland BWV 61 kantáta')
INSERT INTO Pieces (Composer, Title) VALUES ('Bach, Johann Sebastian (1685–1750)', 'Sei Lob und Preis mit Ehren SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Bach, Johann Sebastian (1685–1750)', 'Suscepit Israel – a Magnificat 9. versszaka SSA')
INSERT INTO Pieces (Composer, Title) VALUES ('Bárdos Lajos (1899–1986)', 'Adjunk hálát immár SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Becker, Albert (1834–1899)', 'Befiehl dem Herrn deine Wege SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Bence Gábor (1962–)', 'Hagyjad az Úristenre minden te utadat SAB')
INSERT INTO Pieces (Composer, Title) VALUES ('Bennett, W. S. (1816–1875)', 'Két tétel A samáriai asszony c. kantátából SATB+szólisták')
INSERT INTO Pieces (Composer, Title) VALUES ('Bennett, W. S. (1816–1875)', 'Ó, maradj vélem SATB+org')
INSERT INTO Pieces (Composer, Title) VALUES ('Berthier, Jacques (1923–1994)', 'Jubilate Deo kánon')
INSERT INTO Pieces (Composer, Title) VALUES ('Bourgeois, Louis (1510–1559)', 'Aki a felséges Úrnak – 91. genfi zsoltár SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Boyce, William (1710–1779)', 'Alleluja kánon')
INSERT INTO Pieces (Composer, Title) VALUES ('Brahms, Johannes (1806–1872)', 'Ach, arme Welt SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Brahms, Johannes (1806–1872)', 'Az Úr kezében életem SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Brahms, Johannes (1806–1872)', 'Schaffe in mir Gott, ein rein Herz SATBB')
INSERT INTO Pieces (Composer, Title) VALUES ('Briegel, Wolfgang Karl (1626–1712)', 'Hálát mondva áldunk Téged SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Briegel, Wolfgang Karl (1626–1712)', 'Siehe, dein König kommt SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Bruck, Arnold von (†1554)', 'Christ der ist erstanden SATB (c.f. in T)')
INSERT INTO Pieces (Composer, Title) VALUES ('Bruck, Arnold von (1500–1554)', 'O, du armer Judas SSATBB')
INSERT INTO Pieces (Composer, Title) VALUES ('Bruck, Arnold von (1500–1554)', 'Pater noster SSAA')
INSERT INTO Pieces (Composer, Title) VALUES ('Bruck, Arnold von (1500–1554)', 'Vater unser SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Brunckhorst, Arnold (1670–1725)', 'Dies ist der Tag a Húsvéti történet c. kantátából SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Burgk, Joachim a (1546–1610)', 'Im Garten leidet Christus Not SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Burgk, Joachim a (1546–1610)', 'Wer wollte nun nicht fröhlich sein SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Buxtehude, Dietrich (1637–1707)', 'Cantate Domino kantáta a 96. zsoltárra SSB')
INSERT INTO Pieces (Composer, Title) VALUES ('Buxtehude, Dietrich (1637–1707)', 'Der Herr ist mit mir SATB+zkr')
INSERT INTO Pieces (Composer, Title) VALUES ('Buxtehude, Dietrich (1637–1707)', 'In te, Domine, speravi SAB')
INSERT INTO Pieces (Composer, Title) VALUES ('Buxtehude, Dietrich (1637–1707)', 'Magnificat SSATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Buxtehude, Dietrich (1637–1707)', 'Nun bitten wir den heiligen Geist')
INSERT INTO Pieces (Composer, Title) VALUES ('Búza András (1982–)', 'Jézus, világ Megváltója SAB')
INSERT INTO Pieces (Composer, Title) VALUES ('Byrd, William (1543/4–1623)', 'Haec dies ATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Byrd, William (1543/4–1623)', 'Haec dies quam fecit Dominus SSATTB')
INSERT INTO Pieces (Composer, Title) VALUES ('Byrd, William (1543/4–1623)', 'In resurrectione tua SAATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Byrd, William (1543/4–1623)', 'Laetentur coeli SSATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Byrd, William (1543/4–1623)', 'Laudibus in sanctis Dominum SSATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Byrd, William (1543/4–1623)', 'Ne irascaris, Domine SATTB')
INSERT INTO Pieces (Composer, Title) VALUES ('Byrd, William (1543/4–1623)', 'Sacerdotes Domini SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Byrd, William (1543/4–1623)', 'Siderum rector SSATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Byrd, William (1543/4–1623)', 'Vigilate SATTB')
INSERT INTO Pieces (Composer, Title) VALUES ('Calvisius, Seth (1556–1615)', 'Mint édesatyja asztalát SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Cardoso, Manuel (1569–1650)', 'Aquam quam ego dabo SSATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Celminskis, Mamerts (1912–1993)', 'Gloria tibi Trinitas SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Cima, Giovanni Paolo (1570–1630)', 'O Domine SB')
INSERT INTO Pieces (Composer, Title) VALUES ('Coates, Robert (1954–)', 'Desz-dúr Magnificat SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Croce, Giovanni (1557–1609)', 'Cantate Domino SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Croce, Giovanni (1557–1609)', 'Fájdalmak férfia SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Crüger, Johann (1598–1662)', 'Cantate Domino SAB')
INSERT INTO Pieces (Composer, Title) VALUES ('Crüger, Johann (1598–1662)', 'Ich will bei meinem Leben / Míg én e földön élek SAB')
INSERT INTO Pieces (Composer, Title) VALUES ('Crüger, Johann (1598–1662)', 'Ó, drága Jézus SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Csomasz Tóth Kálmán (1902–1988)', 'Krisztus, ártatlan Bárány SA(T)B')
INSERT INTO Pieces (Composer, Title) VALUES ('Csomasz Tóth Kálmán (1902–1988)', 'Ó, seregeknek Istene – 84. genfi zsoltár SSA')
INSERT INTO Pieces (Composer, Title) VALUES ('Csorba István (1935–)', 'Mert úgy szerette Isten a világot SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Csorba István (1935–)', 'Szállj alá a mennyből SA / TB')
INSERT INTO Pieces (Composer, Title) VALUES ('Dedekind, Constantin Christian (1628–1715)', 'Minden ember téged áld kiskantáta SAB+solo')
INSERT INTO Pieces (Composer, Title) VALUES ('Distler, Hugo (1908–1942)', 'Erhalt uns, Herr SAB')
INSERT INTO Pieces (Composer, Title) VALUES ('Distler, Hugo (1908–1942)', 'Maria durch ein Dornwald ging SAB')
INSERT INTO Pieces (Composer, Title) VALUES ('Domine ad adiuvandum – kánon a Zsigmond-kori töredékből', '')
INSERT INTO Pieces (Composer, Title) VALUES ('Draskóczy László (1940–2020)', 'Az Úr Isten Ádám atyánknak SAB')
INSERT INTO Pieces (Composer, Title) VALUES ('Draskóczy László (1940–2020)', 'Itt van Isten köztünk SAB')
INSERT INTO Pieces (Composer, Title) VALUES ('Draskóczy László (1940–2020)', 'Kegyes Jézus, itt vagyunk TBB')
INSERT INTO Pieces (Composer, Title) VALUES ('Dressler, Gallus (1533–1585)', 'Ich bin die Auferstehung und das Leben SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Dressler, Gallus (1533–1585)', 'Lobet den Herren, alle Heiden SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Drischner, Max (1891–1971)', 'Der Herr ist mein Hirte SAB')
INSERT INTO Pieces (Composer, Title) VALUES ('Dubra, Rihards (1964–)', 'Laudate Dominum – 150. zsoltár SSA')
INSERT INTO Pieces (Composer, Title) VALUES ('Durandus, Caspar Chrysostomus (17. század)', 'Áldunk téged, Isten SAB')
INSERT INTO Pieces (Composer, Title) VALUES ('Durandus, Caspar Chrysostomus (17. század)', 'Halleluja, halleluja ST')
INSERT INTO Pieces (Composer, Title) VALUES ('Duruflé, Maurice (1902–1986)', 'Notre Père SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Eccard, Johann (1553–1611)', 'Der große Tag des Herren SSATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Eccard, Johann (1553–1611)', 'Der Heilig Geist vom Himmel kam SSATTB')
INSERT INTO Pieces (Composer, Title) VALUES ('Eccard, Johann (1553–1611)', 'Herr Christe tu mir geben, was ich nicht nehmen kann SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Eccard, Johann (1553–1611)', 'Im Garten leidet Christus Not SSATTB')
INSERT INTO Pieces (Composer, Title) VALUES ('Eccard, Johann (1553–1611)', 'Kommt her zu mir, spricht Gottes Sohn SATTB')
INSERT INTO Pieces (Composer, Title) VALUES ('Eccard, Johann (1553–1611)', 'Maria wallt zum Heiligtum SSATTB')
INSERT INTO Pieces (Composer, Title) VALUES ('Eccard, Johann (1553–1611)', 'Nun liebe Seel, nun ist es Zeit SSATTB')
INSERT INTO Pieces (Composer, Title) VALUES ('Eccard, Johann (1553–1611)', 'Zacharias war ganz verstummt SSATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Eccard, Johann (1553–1611)', 'Zu dieser österlichen Zeit SSAATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Elgar, Edward (1857–1934)', 'Ave verum corpus natum de Maria Virgine S solo+SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Erich, Ambrosius (16. század)', 'Áldunk téged, Úr Krisztusunk ST')
INSERT INTO Pieces (Composer, Title) VALUES ('Erythräus, Gotthart (1560–1617)', 'Dank sagen wir alle Gott SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Esterházy Pál (1653–1713) gyűjteményéből', 'Dormi Jesu, dulcissime / Szép napunk elérkezett SA')
INSERT INTO Pieces (Composer, Title) VALUES ('Esterházy Pál (1653–1713) gyűjteményéből', 'Jézus eljön nemsokára SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Esterházy Pál (1653–1713) gyűjteményéből', 'Veni creator spiritus SATB+S solo')
INSERT INTO Pieces (Composer, Title) VALUES ('Fauré, Gabriel (1845–1924)', 'Ave verum SA+org')
INSERT INTO Pieces (Composer, Title) VALUES ('Finck, Heinrich (1445–1527)', 'In Gottes Namen fahren wir SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Franck, Cesar (1822–1890)', 'Halld, mily szózat hangzik SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Franck, Cesar (1822–1890)', 'Panis angelicus ST+org')
INSERT INTO Pieces (Composer, Title) VALUES ('Franck, Melchior (1580?–1639)', 'Ach treuer Heiland, Jesu Christ SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Franck, Melchior (1580?–1639)', 'Also hat Gott die Welt geliebt SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Franck, Melchior (1580?–1639)', 'Also werden die Letzten die Ersten sein SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Franck, Melchior (1580?–1639)', 'Also wird euch mein himmlischer Vater auch tun SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Franck, Melchior (1580?–1639)', 'Da nun die Menschen das Zeichen sahen SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Franck, Melchior (1580?–1639)', 'Das aber auf dem guten Land sind, die das hören SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Franck, Melchior (1580?–1639)', 'Der Herr hat gesagt zu meinem Herren SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Franck, Melchior (1580?–1639)', 'Entsetzet euch nicht! SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Franck, Melchior (1580?–1639)', 'Es ist ein großer Prophet unter uns aufgestanden SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Franck, Melchior (1580?–1639)', 'Fürwahr, er trug unsere Krankheit SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Franck, Melchior (1580?–1639)', 'Geh aus auf die Landstraßen und an die Zäune SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Franck, Melchior (1580?–1639)', 'Gehet hin und saget Johanni wieder / Jézus szavai János tanítványaihoz SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Franck, Melchior (1580?–1639)', 'Heb dich weg von mir, Satan! / Távozz el tőlem, Sátán SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Franck, Melchior (1580?–1639)', 'Herr, komm hinab, eh denn mein Kind stirbet SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Franck, Melchior (1580?–1639)', 'Hosianna dem Sohne Davids SSAT')
INSERT INTO Pieces (Composer, Title) VALUES ('Franck, Melchior (1580?–1639)', 'Ich bin ein guter Hirte SSAB')
INSERT INTO Pieces (Composer, Title) VALUES ('Franck, Melchior (1580?–1639)', 'Ich taufe mit Wasser SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Franck, Melchior (1580?–1639)', 'Jedermann gibt zum ersten guten Wein SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Franck, Melchior (1580?–1639)', 'Mein Sohn, warum hast du uns das getan? SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Franck, Melchior (1580?–1639)', 'Nehmet hin den heiligen Geist SSAB')
INSERT INTO Pieces (Composer, Title) VALUES ('Franck, Melchior (1580?–1639)', 'Saget den Gästen')
INSERT INTO Pieces (Composer, Title) VALUES ('Franck, Melchior (1580?–1639)', 'Siehe, dieser wird gesetzt zu einem Fall SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Franck, Melchior (1580?–1639)', 'Trachtet am ersten nach dem Reich Gottes SSAB')
INSERT INTO Pieces (Composer, Title) VALUES ('Franck, Melchior (1580?–1639)', 'Und du, Bethlehem im jüdischen Lande SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Franck, Melchior (1580?–1639)', 'Und er rief und sprach')
INSERT INTO Pieces (Composer, Title) VALUES ('Franck, Melchior (1580?–1639)', 'Wahrlich, ich sage euch')
INSERT INTO Pieces (Composer, Title) VALUES ('Franck, Melchior (1580?–1639)', 'Wahrlich, ich sage euch')
INSERT INTO Pieces (Composer, Title) VALUES ('Franck, Melchior (1580?–1639)', 'Warum denket ihr so Args in eurem Herzen SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Franck, Melchior (1580?–1639)', 'Wenn du geladen wirst, so gehe hin SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Franck, Melchior (1580?–1639)', 'Wer mich liebet, der wird mein Wort halten / Mind, ki szeret SSAT')
INSERT INTO Pieces (Composer, Title) VALUES ('Freundt, Cornelius (1540–1591)', 'Wie schön singt uns der Engel Schar SATB / SSAB')
INSERT INTO Pieces (Composer, Title) VALUES ('Gabrieli, Giovanni (1557–1612)', 'O magnum mysterium SATBx2')
INSERT INTO Pieces (Composer, Title) VALUES ('Gallus, Jacobus (1550–1591)', 'Confirma hoc Deus SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Gallus, Jacobus (1550–1591)', 'Dies ist der Tag SATB.SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Gallus, Jacobus (1550–1591)', 'Domine ad adiuvandum SSA')
INSERT INTO Pieces (Composer, Title) VALUES ('Gallus, Jacobus (1550–1591)', 'O Herre Gott, in meiner Not SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Gárdonyi Zoltán  (1906–1986)', 'Légy hív mindhalálig kánon + org.')
INSERT INTO Pieces (Composer, Title) VALUES ('Gárdonyi Zoltán  (1906–1986)', 'Serkenj föl, aki aluszol kánon')
INSERT INTO Pieces (Composer, Title) VALUES ('Gárdonyi Zoltán (1906–1986)', 'Hagyjad az Úrra kánon')
INSERT INTO Pieces (Composer, Title) VALUES ('Gárdonyi Zoltán (1906–1986)', 'Mondjatok dicséretet SATB+org')
INSERT INTO Pieces (Composer, Title) VALUES ('Gárdonyi Zoltán (1906–1986)', 'Tarts meg, Urunk SSA')
INSERT INTO Pieces (Composer, Title) VALUES ('Gárdonyi Zoltán (1906–1986)', 'Új világosság jelenék SSA')
INSERT INTO Pieces (Composer, Title) VALUES ('Gaul, Harvey Bartlett (1881–1945)', 'Teach us, good Lord SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Geist, Christian (1650–1711)', 'Szép tündöklő hajnalcsillag S solo + zkr')
INSERT INTO Pieces (Composer, Title) VALUES ('Gerzsenyi Sándor (1933–2019)', 'Csillagfényes, csöndes éjjel SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Gesius, Bartholomäus (1560–1613)', 'Ein Kind geborn zu Bethlehem SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Gibbons, Orlando (1583–1625)', 'Almighty and everlasting God SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Gibbons, Orlando (1583–1625)', 'Nunc Dimittis from Short Service SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Gombert, Nicolas (1495– 1560)', 'In Gottes Namen fahren wir SSAA / TTBB')
INSERT INTO Pieces (Composer, Title) VALUES ('Goss, John (1800–1880)', 'Almighty and merciful God SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Goudimel, Claude (1510–1572)', 'Az Úr énnékem őriző pásztorom – 25. genfi zsoltár SATB polifón')
INSERT INTO Pieces (Composer, Title) VALUES ('Goudimel, Claude (1510–1572)', 'Nosza, istenfélő szent hívek – 33. genfi zsoltár SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Goudimel, Claude (1514–1572)', 'Az Isten a mi reménységünk – 46. genfi zsoltár (c.f. in T)')
INSERT INTO Pieces (Composer, Title) VALUES ('Goudimel, Claude (1514–1572)', 'Az Isten a mi reménységünk – 46. genfi zsoltár polifón')
INSERT INTO Pieces (Composer, Title) VALUES ('Goudimel, Claude (1514–1572)', 'Énekeljetek minden népek – 96. genfi zsoltár SATB polifón')
INSERT INTO Pieces (Composer, Title) VALUES ('Goudimel, Claude (1514–1572)', 'Ímé, mily jó és mily nagy gyönyörűség – 133. genfi zsoltár SATB polifón')
INSERT INTO Pieces (Composer, Title) VALUES ('Gumpelzhaimer, Adam (1559–1625)', 'Aller Augen warten auf dich, Herr SSATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Gumpelzhaimer, Adam (1559–1625)', 'Gott Vater uns sein Sohn fürstellt SST')
INSERT INTO Pieces (Composer, Title) VALUES ('Gumpelzhaimer, Adam (1559–1625)', 'Miatyánk-kánon')
INSERT INTO Pieces (Composer, Title) VALUES ('Gumpelzhaimer, Adam (1559–1625)', 'Mit Fried und Freud ich fahr dahin SAT')
INSERT INTO Pieces (Composer, Title) VALUES ('Gumpelzhaimer, Adam (1559–1625)', 'Örvendjetek, keresztyének SAB')
INSERT INTO Pieces (Composer, Title) VALUES ('Gumpelzhaimer, Adam (1559–1625)', 'Wir danken dir, Herr Gott SSATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Gumpelzhaimer, Adam (1559–1625)', 'Zengjen a dal az Úrnak, és örvendj, hívő népe SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Halmos László (1909–1997)', 'Ad te Domine levavi SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Halmos László (1909–1997)', 'Minden földek, Istent dicsérjétek! SSA')
INSERT INTO Pieces (Composer, Title) VALUES ('Hammerschmidt, Andreas  (1612–1675)', 'O, Vater aller Frommen SSTTB')
INSERT INTO Pieces (Composer, Title) VALUES ('Hammerschmidt, Andreas  (1612–1675)', 'Triumph, Triumph, Victoria SSATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Hammerschmidt, Andreas (1611–1675)', 'Schmücket das Fest mit Maien SSATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Hammerschmidt, Andreas (1612–1675)', 'Machet die Tore weit SSAATB (SAB)')
INSERT INTO Pieces (Composer, Title) VALUES ('Händel, Georg Friedrich (1685–1759)', 'Halleluja a Saul c. oratóriumból SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Harmat Artúr (1885–1962)', 'O crux ave SAB')
INSERT INTO Pieces (Composer, Title) VALUES ('Hassler, Hans Leo (1564–1612)', 'Cantate Domino SSATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Hassler, Hans Leo (1564–1612)', 'Jer, örvendjünk, keresztyének SSA')
INSERT INTO Pieces (Composer, Title) VALUES ('Hassler, Hans Leo (1564–1612)', 'Verbum caro factum est ATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Haydn, Johann Michael (1737–1806)', 'Judas mercator pessimus SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Haydn, Joseph (1732–1809)', 'Az Úrra hagyjad utad SAB')
INSERT INTO Pieces (Composer, Title) VALUES ('Haydn, Joseph (1732–1809)', 'Show me your ways – 25. zsoltár SAB')
INSERT INTO Pieces (Composer, Title) VALUES ('Haydn, Michael (1737-1806)', 'Tribulationes cordis mei SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Hayes, Philipp (1738–1797)', 'Hozsánna! SAB')
INSERT INTO Pieces (Composer, Title) VALUES ('Hemmel, Sigmund (1520–1565)', 'Dir, o Herr, will ich singen SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Herzogenberg, Heinrich von (1843–1900)', 'Schmecket und sehet SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Homilius, Gottfried August (1714–1985)', 'Deo dicamus gratias SSATTB')
INSERT INTO Pieces (Composer, Title) VALUES ('Homilius, Gottfried August (1714–1985)', 'Domine, ad adiuvandum me SSATBB')
INSERT INTO Pieces (Composer, Title) VALUES ('Homilius, Gottfried August (1714–1985)', 'Íme, milyen nagy áldás SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Homilius, Gottfried August (1714–1985)', 'Siehe, das ist Gottes Lamm SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Isaac, Heinrich (1450–1517)', 'Ego sum pastor bonus SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Ismeretlen spanyol szerző (16. század)', 'Évnek újulásán SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Ismeretlen szerző (13. sz.)', 'Alleluja, zengjétek szent nevét! SSA')
INSERT INTO Pieces (Composer, Title) VALUES ('Ismeretlen szerző', 'Danket dem Herrn, denn er ist freundlich SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Ismeretlen szerző', 'Lobe den Herrn, meine Seele SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Jeune, Claude le (1530–1600)', 'Mint a szép híves patakra SATB (c. f. in T)')
INSERT INTO Pieces (Composer, Title) VALUES ('Kapi Gyula (1850–1923) – Kapi-Králik Jenő (1906–1978)', 'Könyörülj, Úristen mirajtunk SATB+org')
INSERT INTO Pieces (Composer, Title) VALUES ('Katada, Yui (1985–)', 'Ó, jöjj, ó, jöjj, Immánuel ')
INSERT INTO Pieces (Composer, Title) VALUES ('Kickstat, Paul (1893–1959)', 'Soli Deo gloria kánon')
INSERT INTO Pieces (Composer, Title) VALUES ('Kindermann, Johann Erasmus (1616–1655)', 'Mennybéli áldott Istenünk SAB')
INSERT INTO Pieces (Composer, Title) VALUES ('Klemetti, Heikki (1876–1953)', 'A dextris Dei SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Klemetti, Heikki (1876–1953)', 'Christus pro nobis passus est SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Knab, Armin (1881–1951)', 'Mitten wir im Leben sind SAB')
INSERT INTO Pieces (Composer, Title) VALUES ('Knüpfer, Sebastian (1633–1676)', 'A mennyből jövök hozzátok SSS + zkr')
INSERT INTO Pieces (Composer, Title) VALUES ('Kocsár Miklós (1933–2019)', 'Két tétel az Ó, gyönyörűszép, titokzatos éj. Karácsonyi énekek nőikarra c. gyűjteményből (Csordapásztorok és Kirie elejszon) SSA')
INSERT INTO Pieces (Composer, Title) VALUES ('Kodály Zoltán (1882–1967)', 'Adventi ének SA(T)B')
INSERT INTO Pieces (Composer, Title) VALUES ('Kostiainen, Pekka (1944–)', 'Verbum caro factum est a Piae Cantiones (1582) gyűjteményből SSAA')
INSERT INTO Pieces (Composer, Title) VALUES ('Krieger, Johann Philipp (1649–1725)', 'Die Welt kann den Geist der Wahrheit nicht empfangen – dialóguskantáta B solo+SAB')
INSERT INTO Pieces (Composer, Title) VALUES ('Krieger, Johann Philipp (1649–1725)', 'Lehre mich tun, nach deinem Wohlgefallen SA')
INSERT INTO Pieces (Composer, Title) VALUES ('Krieger, Johann Philipp (1649–1725)', 'Schaff in mir, Gott ein reines Herz SAB')
INSERT INTO Pieces (Composer, Title) VALUES ('Kugelmann, Johann (1616–1655)', 'Az ég és föld Urának SAB')
INSERT INTO Pieces (Composer, Title) VALUES ('Kugelmann, Johann (1616–1655)', 'Erős vár a mi Istenünk SAB')
INSERT INTO Pieces (Composer, Title) VALUES ('Kugelmann, Paul (?–1580)', 'Benedicamus a 6')
INSERT INTO Pieces (Composer, Title) VALUES ('Lasso, Orlando di (1532–1594)', 'Adoramus te, Christe / Áldunk Téged, Úr Krisztus a Magnum opus musicum gyűjteményből SSA')
INSERT INTO Pieces (Composer, Title) VALUES ('Lasso, Orlando di (1532–1594)', 'Agimus tibi gratias a Magnum opus musicum gyűjteményből SSA')
INSERT INTO Pieces (Composer, Title) VALUES ('Lasso, Orlando di (1532–1594)', 'Domine Deus / Úristen áldunk SA')
INSERT INTO Pieces (Composer, Title) VALUES ('Lasso, Orlando di (1532–1594)', 'Jauchzet Gott, alle Lande / Énekelj az Úrnak  SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Lasso, Orlando di (1532–1594)', 'Magnificat primi toni SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Lasso, Orlando di (1532–1594)', 'Oculus non vidit SB')
INSERT INTO Pieces (Composer, Title) VALUES ('Lasso, Orlando di (1532–1594)', 'Ujjongván az Úrban a Magnum opus musicum gyűjteményből SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Lau, Heinz (1925–1975)', 'Wer sich die Musik erkiest – kánon Luther versére')
INSERT INTO Pieces (Composer, Title) VALUES ('Lechner, Leonhardt (1550–1606)', 'Historia der Passion und Leidens unsers einigen Erlösers und Seligmachers Jesu Christi SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Lechner, Leonhardt (1550–1606)', 'Már nyugosznak a völgyek SAB')
INSERT INTO Pieces (Composer, Title) VALUES ('Lechner, Leonhardt (1550–1606)', 'Nun schein du Glanz der Herrlichkeit SSATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Lepnurm, Hugo (1914–1999)', 'Szép, fényes hajnalcsillagom')
INSERT INTO Pieces (Composer, Title) VALUES ('Liebhold-nál (†1730)', 'Az Úrra hagyjad minden dolgod SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Ligeti György (1923–2006)', 'Ha folyóvíz volnék a Két kánonból')
INSERT INTO Pieces (Composer, Title) VALUES ('Ligeti György (1923–2006)', 'Húsvét (részlet) SSMAA')
INSERT INTO Pieces (Composer, Title) VALUES ('Liszt Ferenc (1811–1886)', 'Él a Krisztus SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Loewe, Carl (1796–1869)', 'Kleine Passionsmusik SATB + zkr')
INSERT INTO Pieces (Composer, Title) VALUES ('Lotti, Antonio (1666–1740)', 'Úr Jézus Krisztus feltámadt SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Lotti, Antonio (1666–1740)', 'Vere languores nostros SAB')
INSERT INTO Pieces (Composer, Title) VALUES ('Maistre, Matthäus Le (1505–1577)', 'Aller Augen warten auf dich, Herr SAT')
INSERT INTO Pieces (Composer, Title) VALUES ('Maistre, Matthäus Le (1505–1577)', 'Tarts meg, Urunk, szent igédben SAT')
INSERT INTO Pieces (Composer, Title) VALUES ('Martini, Giovanni Battista (1706–1784)', 'Jöjj, várlak, drága Jézusom! SSA')
INSERT INTO Pieces (Composer, Title) VALUES ('Mendelssohn Bartholdy, Felix (1809–1847)', 'Abendsegen / Herr sei gnädig SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Mendelssohn Bartholdy, Felix (1809–1847)', 'Hebe deine Augen auf / Bízva nézz a bércre fel tercett az Illés c. oratóriumból SSA')
INSERT INTO Pieces (Composer, Title) VALUES ('Mendelssohn Bartholdy, Felix (1809–1847)', 'Jauchzet dem Herren SATB/2×')
INSERT INTO Pieces (Composer, Title) VALUES ('Mendelssohn Bartholdy, Felix (1809–1847)', 'Jól tudom, mily gyarló szó az én imádságom SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Mendelssohn Bartholdy, Felix (1809–1847)', 'Nunc dimittis (Herr, nun lässest du) SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Mendelssohn Bartholdy, Felix (1809–1847)', 'Sechs Sprüche n')
INSERT INTO Pieces (Composer, Title) VALUES ('Mendelssohn Bartholdy, Felix (1809–1847)', 'Trauergesang SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Mendelssohn Bartholdy, Felix (1809–1847)', 'Veni Domine SSA+org')
INSERT INTO Pieces (Composer, Title) VALUES ('Menegali (18–19. század)', 'Jesu, salvator mundi SAB')
INSERT INTO Pieces (Composer, Title) VALUES ('Monteverdi, Claudio (1567–1643)', 'Áldjátok az Urat SSA')
INSERT INTO Pieces (Composer, Title) VALUES ('Monteverdi, Claudio (1567–1643)', 'Angelus ad pastores ait SSA')
INSERT INTO Pieces (Composer, Title) VALUES ('Monteverdi, Claudio (1567–1643)', 'Cantate Domino SSATTB')
INSERT INTO Pieces (Composer, Title) VALUES ('Monteverdi, Claudio (1567–1643)', 'Ó, áldott, drága Jézus Krisztus SSA')
INSERT INTO Pieces (Composer, Title) VALUES ('Morley Thomas (c.1557–1602)', 'Nolo mortem peccatoris SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Mozart, W. A. (1756–1791)', 'Beatus vir qui timet Dominum SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Mozart, W. A. (1756–1791)', 'Davidde penitente SST soli + SATB + zkr')
INSERT INTO Pieces (Composer, Title) VALUES ('Mozart, W. A. (1756–1791)', 'Grabmusik S, B soli + SATB + zkr')
INSERT INTO Pieces (Composer, Title) VALUES ('Mozart, W. A. (1756–1791)', 'Halljad, néped mint sóhajt SAB')
INSERT INTO Pieces (Composer, Title) VALUES ('Mozart, W. A. (1756–1791)', 'Jubilate Deo omnis terra SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Mozart, W. A. (1756–1791)', 'Laudate Dominum – 117. zsoltár S solo + SATB + org')
INSERT INTO Pieces (Composer, Title) VALUES ('Mozart, W. A. (1756–1791)', 'Missa brevis (Kyrie, Gloria)')
INSERT INTO Pieces (Composer, Title) VALUES ('Náray Máté (1988–)', 'Kyrie SAB')
INSERT INTO Pieces (Composer, Title) VALUES ('Nicolson, Richard (1570–1639)', 'Cantate Domino SSATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Nunc dimittis – Simeon hálaéneke Lk 2 alapján, Szenczi Molnár Albert magyar szövegével SATB', '')
INSERT INTO Pieces (Composer, Title) VALUES ('Nystedt, Knut (1915–2014)', 'I will praise thee, o Lord SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Ó, kicsinyke Betlehem, városok közt legnagyobb', 'Középkori kanció 2sz.')
INSERT INTO Pieces (Composer, Title) VALUES ('Osváth Viktor (1921–1985)', 'Itt az Isten köztünk SAB')
INSERT INTO Pieces (Composer, Title) VALUES ('Othmayr, Kaspar (1515–1553)', 'Bizony meglészen az idő bicinium')
INSERT INTO Pieces (Composer, Title) VALUES ('Othmayr, Kaspar (1515–1553)', 'Bűnünkért tenger sok a könny SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Othmayr, Kaspar (1515–1553)', 'Erős vár a mi Istenünk bicinium')
INSERT INTO Pieces (Composer, Title) VALUES ('Othmayr, Kaspar (1515–1553)', 'Jöjj, áldott nagy Királyunk / Krisztus Atyaistennek egyetlenegy fia bicinium')
INSERT INTO Pieces (Composer, Title) VALUES ('Othmayr, Kaspar (1515–1553)', 'Mitten wir im Leben sind bicinium')
INSERT INTO Pieces (Composer, Title) VALUES ('Othmayr, Kaspar (1515–1553)', 'O Mensch, bewein dein Sünde groß SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Othmayr, Kaspar (1515–1553)', 'Ó, teremtő Atya Isten bicinium')
INSERT INTO Pieces (Composer, Title) VALUES ('Othmayr, Kaspar (1515–1553)', 'Örvendezek benned SS')
INSERT INTO Pieces (Composer, Title) VALUES ('Pachelbel, Johann (1653–1706)', 'Gott ist unser Zuversicht SATB.SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Palestrina, Giovanni P. da (1526–1594)', 'Adoramus te, Christe  SSAA')
INSERT INTO Pieces (Composer, Title) VALUES ('Palestrina, Giovanni P. da (1526–1594)', 'Benedicta sit sancta Trinitas SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Palestrina, Giovanni P. da (1526–1594)', 'Improperium exspectavit cor meum SSATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Palestrina, Giovanni P. da (1526–1594)', 'Jesu, rex admirabilis SAT')
INSERT INTO Pieces (Composer, Title) VALUES ('Palestrina, Giovanni P. da (1526–1594)', 'Lauda Sion Salvatorem SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Palestrina, Giovanni P. da (1526–1594)', 'Quae est ista SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Palestrina, Giovanni P. da (1526–1594)', 'Sicut cervus desiderat SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Palestrina, Giovanni P. da (1526–1594)', 'Úr Krisztus, hála néked SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Perti, Giacomo Antonio (1661–1756)', 'Adoramus te, Christe SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Philips, Peter (1565–1628)', 'Ascendit Deus SSATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Pitoni, Giuseppe Ottavio (1657–1743)', 'Szárnyaljon énekünk SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Praetorius, Hieronymus (1560–1629)', 'Also hat Gott die Welt geliebt SSATTB')
INSERT INTO Pieces (Composer, Title) VALUES ('Praetorius, Hieronymus (1560–1629)', 'Kyrie SSATTB')
INSERT INTO Pieces (Composer, Title) VALUES ('Praetorius, Michael (1571–1621)', 'Alleluja kánon')
INSERT INTO Pieces (Composer, Title) VALUES ('Praetorius, Michael (1571–1621)', 'Aus tiefer Not SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Praetorius, Michael (1571–1621)', 'Enatus est Emanuel SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Praetorius, Michael (1571–1621)', 'Feltámadt Krisztus, vigadjunk SAB')
INSERT INTO Pieces (Composer, Title) VALUES ('Praetorius, Michael (1571–1621)', 'Gloria SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Praetorius, Michael (1571–1621)', 'Hála légyen fönn az égben az Istennek! SAB')
INSERT INTO Pieces (Composer, Title) VALUES ('Praetorius, Michael (1571–1621)', 'Jesus Christus, unser Heiland AT')
INSERT INTO Pieces (Composer, Title) VALUES ('Praetorius, Michael (1571–1621)', 'Jézus Krisztus, mi Megváltónk SSA')
INSERT INTO Pieces (Composer, Title) VALUES ('Praetorius, Michael (1571–1621)', 'Krisztus, ki vagy nap és világ SAB')
INSERT INTO Pieces (Composer, Title) VALUES ('Praetorius, Michael (1571–1621)', 'Küldé az Úr Isten SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Praetorius, Michael (1571–1621)', 'Kyrie eleison SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Praetorius, Michael (1571–1621)', 'Midőn eljön az én órám SAB')
INSERT INTO Pieces (Composer, Title) VALUES ('Praetorius, Michael (1571–1621)', 'Most, Uram, elbocsátod SATB.SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Praetorius, Michael (1571–1621)', 'Sanctus SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Praetorius, Michael (1571–1621)', 'Úristen, e napon téged áldunk SAB')
INSERT INTO Pieces (Composer, Title) VALUES ('Prés, Josquin des (1450–1521)', 'Jöjj el, Szentlélek SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Prés, Josquin des (1450–1521)', 'O Jesu, fili David, miserere mei SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Purcell, Henry (1659–1695)', 'Come, Come, ye Sons of Art SSA')
INSERT INTO Pieces (Composer, Title) VALUES ('Purcell, Henry (1659–1695)', 'Lord, How Long Wilt Thou be Angry SSATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Purcell, Henry (1659–1695)', 'Nunc dimittis SSATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Purcell, Henry (1659–1695)', 'Thou knowest, Lord SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Rasch, Johannes (1540–1612)', 'Christ ist erstanden SS')
INSERT INTO Pieces (Composer, Title) VALUES ('Raselius, Andreas (1563–1602)', 'Also hat Gott die Welt geliebt SATB.SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Raselius, Andreas (1563–1602)', 'Wir glauben all an einen Gott / Mi valljuk, hiszünk Istenben SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Rauch, Andreas (1592–1656)', 'Spiritus Domini super me SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Resinarius, Balthasar (1486–1567)', 'Erhalt uns, Herr, bei deinem Wort (Verleih uns Frieden) SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Resinarius, Balthasar (1486–1567)', 'Wir glauben all an einen Gott / Mi valljuk, hiszünk Istenben ATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Rezessy László (1912–1997)', 'Jézus, én bizodalmam SSA')
INSERT INTO Pieces (Composer, Title) VALUES ('Rezessy László (1912–1997)', 'Királyi zászló jár elöl SA')
INSERT INTO Pieces (Composer, Title) VALUES ('Rezessy László (1912–1997)', 'Krisztus feltámadt SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Rezessy László (1912–1997)', 'Szép hajnalcsillag SAB')
INSERT INTO Pieces (Composer, Title) VALUES ('Ruppel, Paul Ernst (1913–2006)', 'Áldunk, Jézusunk – kánon egy Buxtehude-témára')
INSERT INTO Pieces (Composer, Title) VALUES ('Scheidt, Samuel (1587–1654)', 'Bleib bei uns, Herr SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Schein, Johann Hermann (1586–1630) nyomán', 'Christ unser Herr zum Jordan kam SA')
INSERT INTO Pieces (Composer, Title) VALUES ('Schein, Johann Hermann (1586–1630) nyomán', 'Schmücket das Fest mit Maien SAB')
INSERT INTO Pieces (Composer, Title) VALUES ('Schein, Johann Hermann (1586–1630)', 'Heut triumphieret Gottes Sohn / Feltámadt Isten szent fia SSATTB')
INSERT INTO Pieces (Composer, Title) VALUES ('Schein, Johann Hermann (1586–1630)', 'Ich freue mich im Herren SSATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Schein, Johann Hermann (1586–1630)', 'Ich lasse dich nicht SSATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Schein, Johann Hermann (1586–1630)', 'O Herr, ich bin dein Knecht / Szolgád, az vagyok én SSATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Schein, Johann Hermann (1586–1630)', 'Was mein Gott will / Meghajtom térdem SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Schein, Johann Hermann (1586–1630)', 'Wenn wir in höchsten Nöten sein / Úristen, most eléd lépek nőikar')
INSERT INTO Pieces (Composer, Title) VALUES ('Schmidlin, Johannes (1722–1772)', 'Jöjj, áldjad az Istent SAB')
INSERT INTO Pieces (Composer, Title) VALUES ('Schröter, Leonhart (1532–1601)', 'Lobt Gott, ihr Christen, alle gleich SSATB (c.f. in T)')
INSERT INTO Pieces (Composer, Title) VALUES ('Schütz, Heinrich (1585–1672)', 'A feltámadt Krisztust dicsérje szívünk és szánk SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Schütz, Heinrich (1585–1672)', 'A föltámadás története magyar nyelven Soli + SATB + zkr')
INSERT INTO Pieces (Composer, Title) VALUES ('Schütz, Heinrich (1585–1672)', 'Also hat Gott die Welt geliebt SATTB')
INSERT INTO Pieces (Composer, Title) VALUES ('Schütz, Heinrich (1585–1672)', 'Auf dich traue ich SSATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Schütz, Heinrich (1585–1672)', 'Bringt her den Herren S solo')
INSERT INTO Pieces (Composer, Title) VALUES ('Schütz, Heinrich (1585–1672)', 'Cantate Domino SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Schütz, Heinrich (1585–1672)', 'Das Blut Jesu Christi SSB')
INSERT INTO Pieces (Composer, Title) VALUES ('Schütz, Heinrich (1585–1672)', 'Der Engel sprach SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Schütz, Heinrich (1585–1672)', 'Der Herr ist mein getreuer Hirt – 23. Becker-zsoltár SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Schütz, Heinrich (1585–1672)', 'Der Herr ist mein Hirt (a Symphoniae sacrae 3. kötetéből) SAT solo + SATB + zkr')
INSERT INTO Pieces (Composer, Title) VALUES ('Schütz, Heinrich (1585–1672)', 'Die Gottseligkeit SAB')
INSERT INTO Pieces (Composer, Title) VALUES ('Schütz, Heinrich (1585–1672)', 'Die Himmel erzählen die Ehre Gottes – 19. zsoltár SSATTB')
INSERT INTO Pieces (Composer, Title) VALUES ('Schütz, Heinrich (1585–1672)', 'Die mit Tränen säen SSATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Schütz, Heinrich (1585–1672)', 'Ehre sei die, Christe (a Máté-passió zárókórusa) SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Schütz, Heinrich (1585–1672)', 'Eile mich, Gott, zu erretten S')
INSERT INTO Pieces (Composer, Title) VALUES ('Schütz, Heinrich (1585–1672)', 'Es ist erschienen die heilsame Gnade Gottes SSATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Schütz, Heinrich (1585–1672)', 'Feget den alten Sauerteig aus SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Schütz, Heinrich (1585–1672)', 'Gib unsern Fürsten SSATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Schütz, Heinrich (1585–1672)', 'Herr, auf dich traue ich SSATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Schütz, Heinrich (1585–1672)', 'Hozzád megyek, én Jézusom')
INSERT INTO Pieces (Composer, Title) VALUES ('Schütz, Heinrich (1585–1672)', 'Ich bin die Auferstehung und das Leben SATB.SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Schütz, Heinrich (1585–1672)', 'Ich bin ein rechter Weinstock SSATTB')
INSERT INTO Pieces (Composer, Title) VALUES ('Schütz, Heinrich (1585–1672)', 'Ich weiss, dass mein Erlöser lebt SSAATBB')
INSERT INTO Pieces (Composer, Title) VALUES ('Schütz, Heinrich (1585–1672)', 'Ihr Heiligen lobsinget den Herren SS')
INSERT INTO Pieces (Composer, Title) VALUES ('Schütz, Heinrich (1585–1672)', 'Ist Gott für uns, wer mag wieder uns sein? SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Schütz, Heinrich (1585–1672)', 'János-passió magyar nyelven S, 2 T, 2 B soli + SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Schütz, Heinrich (1585–1672)', 'Jauchzet dem Herren / Hívek, szent nap derült rátok SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Schütz, Heinrich (1585–1672)', 'Jauchzet dem Herren SATB.SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Schütz, Heinrich (1585–1672)', 'Jézus Krisztus hét szava a keresztfán S, A, 3 T, 2 B soli + SATB + zkr')
INSERT INTO Pieces (Composer, Title) VALUES ('Schütz, Heinrich (1585–1672)', 'Karácsonyi történet / A mi Urunk, Jézus Krisztus születésének története')
INSERT INTO Pieces (Composer, Title) VALUES ('Schütz, Heinrich (1585–1672)', 'Lobet den Herren meine Seele SATB.SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Schütz, Heinrich (1585–1672)', 'Lukács-passió S, A, 4 T, 4 B soli + SATB ')
INSERT INTO Pieces (Composer, Title) VALUES ('Schütz, Heinrich (1585–1672)', 'Ó, áldott Jézus Krisztusunk SSA')
INSERT INTO Pieces (Composer, Title) VALUES ('Schütz, Heinrich (1585–1672)', 'O, lieber Herre Gott SS')
INSERT INTO Pieces (Composer, Title) VALUES ('Schütz, Heinrich (1585–1672)', 'Rorate caeli SSB')
INSERT INTO Pieces (Composer, Title) VALUES ('Schütz, Heinrich (1585–1672)', 'Selig sind die Toten SSATTB')
INSERT INTO Pieces (Composer, Title) VALUES ('Schütz, Heinrich (1585–1672)', 'Singet dem Herrn ein neues Lied / Új ének zengje szent nevét – 96. Becker-zsoltár SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Schütz, Heinrich (1585–1672)', 'Singet dem Herrn ein neues Lied SATB.SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Schütz, Heinrich (1585–1672)', 'So fahr ich hin zu Jesu Christ SSATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Schütz, Heinrich (1585–1672)', 'Unser keiner lebet ihm selber SSATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Schütz, Heinrich (1585–1672)', 'Vater unser SATB.SATTB')
INSERT INTO Pieces (Composer, Title) VALUES ('Schütz, Heinrich (1585–1672)', 'Veni Sancte Spiritus 4 együttesre')
INSERT INTO Pieces (Composer, Title) VALUES ('Schütz, Heinrich (1585–1672)', 'Verleih uns Frieden SSATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Schütz, Heinrich (1585–1672)', 'Wohl dem, der nicht wandelt im Rath der Gottlosen SA')
INSERT INTO Pieces (Composer, Title) VALUES ('Schütz, Heinrich (1585–1672)', 'Zeige mir, Herr, den Weg deiner Rechte („He und Vav”) – 119. zsoltár SATB.SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Staden, Johann (1581–1634)', 'Aller Augen warten auf dich, Herr SSA')
INSERT INTO Pieces (Composer, Title) VALUES ('Staden, Johann (1581–1634)', 'Das Vaterunser SSA')
INSERT INTO Pieces (Composer, Title) VALUES ('Staden, Johann (1581–1634)', 'Lobet den Herren alle Heiden SSA')
INSERT INTO Pieces (Composer, Title) VALUES ('Staden, Johann (1581–1634)', 'Mily jó őt dicsérni SSA')
INSERT INTO Pieces (Composer, Title) VALUES ('Staden, Johann (1581–1634)', 'O, Jesu Christ, mein Gott und Herr SSATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Staden, Johann (1581–1634)', 'Zengjen az Úrnak hálaszó SAB')
INSERT INTO Pieces (Composer, Title) VALUES ('Stern, Hermann (1912–1977)', 'Das Volk, das im Finstern wandelt SA')
INSERT INTO Pieces (Composer, Title) VALUES ('Stölzel, Gottfried Heinrich (1690–1749)', 'Te Deum 1–5. és 11. tétel SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Sulyok Imre (1912–2008)', 'A farizeus és a vámszedő SAB')
INSERT INTO Pieces (Composer, Title) VALUES ('Sulyok Imre (1912–2008)', 'Ártatlanság szent Báránya SAB')
INSERT INTO Pieces (Composer, Title) VALUES ('Sulyok Imre (1912–2008)', 'Bízom tebenned, szent Isten SA')
INSERT INTO Pieces (Composer, Title) VALUES ('Sulyok Imre (1912–2008)', 'Boldogok a holtak SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Sulyok Imre (1912–2008)', 'Feljött már a csillag, leszállott az est SA')
INSERT INTO Pieces (Composer, Title) VALUES ('Sulyok Imre (1912–2008)', 'Kínok árnyékaiból SATB+org')
INSERT INTO Pieces (Composer, Title) VALUES ('Sulyok Imre (1912–2008)', 'Mily kedvesek a te hajlékaid – 84. zsoltár SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Sulyok Imre (1912–2008)', 'Semmit ne bánkódjál SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Sweelinck, Jan Pieterszoon (1562–1620)', 'Az Isten óv és karján hordoz engem – 23. genfi zsoltár')
INSERT INTO Pieces (Composer, Title) VALUES ('Sweelinck, Jan Pieterszoon (1562–1620)', 'Énekeljetek minden népek – 96. genfi zsoltár polifón SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Sweelinck, Jan Pieterszoon (1562–1620)', 'Hallgasd meg, Izráel pásztora – 80. genfi zsoltár polifón SATTB')
INSERT INTO Pieces (Composer, Title) VALUES ('Sweelinck, Jan Pieterszoon (1562–1620)', 'Szemem az égre emelem – 121. genfi zsoltár polifón SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Szokolay Sándor (1931–2013)', '23. zsoltár (n')
INSERT INTO Pieces (Composer, Title) VALUES ('Szokolay Sándor (1931–2013)', 'Dicsérjed Istened, ó, én lelkem SAB')
INSERT INTO Pieces (Composer, Title) VALUES ('Tallis, Thomas (1505–1585)', 'Audivi vocem de caelo SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Tallis, Thomas (1505–1585)', 'O Lord, give thy Holy Spirit to our hearts / Uram, add Szentlelkedet! SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Telemann, Georg Philipp (1681–1767)', 'Also hat Gott die Welt geliebt SAB')
INSERT INTO Pieces (Composer, Title) VALUES ('Telemann, Georg Philipp (1681–1767)', 'Ein feste Burg ist unser Gott korálmotetta SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Telemann, Georg Philipp (1681–1767)', 'Ew''ge Quelle, milder Strom szólókantáta')
INSERT INTO Pieces (Composer, Title) VALUES ('Telemann, Georg Philipp (1681–1767)', 'Ha kél a nap SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Telemann, Georg Philipp (1681–1767)', 'Heilig ist Gott, der Herr SA')
INSERT INTO Pieces (Composer, Title) VALUES ('Telemann, Georg Philipp (1681–1767)', 'Húsvéti ária')
INSERT INTO Pieces (Composer, Title) VALUES ('Telemann, Georg Philipp (1681–1767)', 'Ich will den Herrn loben alle Zeit kánon')
INSERT INTO Pieces (Composer, Title) VALUES ('Telemann, Georg Philipp (1681–1767)', 'Jauchzet, ihr Himmel SAB')
INSERT INTO Pieces (Composer, Title) VALUES ('Telemann, Georg Philipp (1681–1767)', 'Lobet den Herrn, alle Heiden – 117. zsoltár SAB')
INSERT INTO Pieces (Composer, Title) VALUES ('Telemann, Georg Philipp (1681–1767)', 'Lukács-passió T, Bar solo + SATB + zkr')
INSERT INTO Pieces (Composer, Title) VALUES ('Telemann, Georg Philipp (1681–1767)', 'Machet die Tore weit kantáta STB soli + SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Telemann, Georg Philipp (1681–1767)', 'Schmückt das frohe Fest mit Maien szólókantáta')
INSERT INTO Pieces (Composer, Title) VALUES ('Telemann, Georg Philipp (1681–1767)', 'Unser keiner lebet ihm selber SAB')
INSERT INTO Pieces (Composer, Title) VALUES ('Telemann, Georg Philipp (1681–1767)', 'Wandelt in der Liebe szólókantáta')
INSERT INTO Pieces (Composer, Title) VALUES ('Telemann, Georg Philipp (1681–1767)', 'Wie lieblich sind deine Wohnungen SAB')
INSERT INTO Pieces (Composer, Title) VALUES ('Tillai Aurél (1930–)', 'Fogadj be, Uram SAB + org.')
INSERT INTO Pieces (Composer, Title) VALUES ('Tillai Aurél (1930–)', 'Lauda Sion SSAA')
INSERT INTO Pieces (Composer, Title) VALUES ('Tóth Árpád (1982–)', 'O, magnum mysterium SS soli + SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Tóth Árpád (1982–)', 'Ubi caritas SS soli + SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Várkonyi András Péter (1974–)', 'Paradicsom mezejibe – népi imádságokra 6sz. nőikar')
INSERT INTO Pieces (Composer, Title) VALUES ('Vaughan Williams, Ralph (1872–1958)', 'O taste and see S solo + SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Victoria, Tomás Luis de (1548–1611)', 'Lauda Sion Salvatorem SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Victoria, Tomás Luis de (1548–1611)', 'O quam gloriosum est / Ó, mily dicsőséges SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Victoria, Tomás Luis de (1548–1611)', 'O quam metuendus est SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Victoria, Tomás Luis de (1548–1611)', 'O sacrum convivium SSSAA')
INSERT INTO Pieces (Composer, Title) VALUES ('Victoria, Tomás Luis de (1548–1611)', 'Vere languores nostros SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Vierdanck, Johann (1605–1646)', 'Jauchzet dem Herren / Ujjongj az Úrnak SAB')
INSERT INTO Pieces (Composer, Title) VALUES ('Vulpius, Melchior (1570–1615)', 'Az élet nekem Krisztus SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Vulpius, Melchior (1570–1615)', 'Dum complerentur dies Pentecostes SSAT')
INSERT INTO Pieces (Composer, Title) VALUES ('Vulpius, Melchior (1570–1615)', 'Erős vár a mi Istenünk SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Vulpius, Melchior (1570–1615)', 'Es werden nicht alle, die zu mir sagen SSATTB')
INSERT INTO Pieces (Composer, Title) VALUES ('Vulpius, Melchior (1571–1615)', 'Wer mich liebet, der wird mein Wort halten SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Walter, Johann (1496–1570)', 'Dicséret zengjen ajkunkon SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Walter, Johann (1496–1570)', 'Herr Gott wenn ich dich hab allein SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Walter, Johann (1496–1570)', 'Jer, örvendjünk, keresztyének SSA')
INSERT INTO Pieces (Composer, Title) VALUES ('Walter, Johann (1496–1570)', 'Nun bitten wir dem heiligen Geist SATTB')
INSERT INTO Pieces (Composer, Title) VALUES ('Walter, Johann', 'Allein auf Gottes Wort SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Webbe, Samuel (1740–1816)', 'Agnus Dei a d-moll miséből SA+org')
INSERT INTO Pieces (Composer, Title) VALUES ('Webbe, Samuel (1740–1816)', 'Kyrie a d-moll miséből SAB+org')
INSERT INTO Pieces (Composer, Title) VALUES ('Weelkes, Thomas (1576–1623)', 'Hosanna to the son of David SSATBB')
INSERT INTO Pieces (Composer, Title) VALUES ('Weltler Jenő (1909–1992)', 'Ó, maradj vélem SATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Young, Gordon (1919–1998)', 'Alleluia SSATB')
INSERT INTO Pieces (Composer, Title) VALUES ('Zachow, Friedrich Wilhelm (1663–1712)', 'Kyrie SATB')
